/* Brazil Abroad — Ocean Edition · Design constants */

export const PAL = {
  oceanDeep: '#051C36',
  ocean:     '#0A2540',
  oceanMid:  '#0F4C81',
  oceanLite: '#2B6FA8',
  gold:      '#D4A574',
  goldWarm:  '#E8B86D',
  goldDeep:  '#B5894F',
  coral:     '#FF8C7A',
  coralSoft: '#FFAB91',
  pink:      '#FF6B9D',
  cream:     '#F8F1E5',
  creamWarm: '#FBF5EB',
  pearl:     '#FFFCF6',
  brYellow:  '#FFD466',
  brGreen:   '#4FB58F',
  text:      '#DDE5EE',
  muted:     '#8FA4BC',
} as const;

export const BOOKING_URL = '#agendar';

export const SOCIAL = {
  whatsapp:  'https://wa.me/5571999990000?text=Oi!%20Vim%20pelo%20site%20do%20Brazil%20Abroad',
  instagram: 'https://instagram.com/brazilabroad',
  youtube:   'https://youtube.com/@brazilabroad',
  linkedin:  'https://linkedin.com/company/brazilabroad',
  tiktok:    'https://tiktok.com/@brazilabroad',
  email:     'mailto:contato@brazilabroad.com',
  phone:     'tel:+5571300000000',
};

export const STR = {
  pt: {
    nav: { mentors: 'Mentores', road: 'Como funciona', apps: 'Apps de IA', gallery: 'Blog', trusted: 'Parceiros', start: 'Falar no WhatsApp' },
    hero: {
      kicker: 'Hub de mentoria · brasileiros pelo mundo',
      title1: 'Seu inglês,',
      title2: 'sua carreira lá fora.',
      sub1: 'Conectamos brasileiros a mentores experientes em cruzeiros, hotéis 5★ e restaurantes premiados.',
      sub2: 'Inglês é a ferramenta. A carreira é o destino.',
      cta1: 'Falar com um mentor',
      cta2: 'Como funciona',
      scroll: 'Role para descobrir',
    },
    stats: {
      kicker: 'Por que somos diferentes',
      title1: 'Não é curso.',
      title2: 'É mentoria real.',
      label1: 'Ganho médio mensal dos nossos alunos lá fora',
      label2: 'Mentores ativos · cruzeiros, Dubai, Europa',
      label3: 'Anos somados de experiência da nossa rede',
      label4: 'Brasileiros guiados em carreira internacional',
    },
    mentors: {
      kicker: 'Nossa rede de mentores',
      title1: 'Quem',
      title2: 'te guia.',
      sub: 'Profissionais brasileiros vivendo a carreira internacional. Eles já passaram por onde você quer chegar.',
      list: [
        { name: 'Ricardo Rogério', role: 'Fundador · Maître Atlantis Dubai', tag: '15 anos · Dubai', bio: 'Hospitalidade de luxo do Brasil ao Oriente Médio.' },
        { name: 'Carla Mendes', role: 'F&B Manager · MSC Cruises', tag: '8 anos no mar', bio: 'Mais de 60 países visitados em contratos de cruzeiros.' },
        { name: 'Diego Almeida', role: 'Head Server · Amazónico Dubai', tag: 'Fine dining', bio: 'De Salvador para os melhores restaurantes do mundo.' },
        { name: 'Letícia Ramos', role: 'Guest Relations · Hilton 5★', tag: 'Europa', bio: 'Inglês fluente, carreira em três continentes.' },
      ],
    },
    road: {
      kicker: 'Como funciona · cinco passos',
      title1: 'Sua',
      title2: 'jornada de mentoria.',
      steps: [
        { t: 'Conversa inicial · WhatsApp', d: 'Você fala com nosso time. A gente ouve seu objetivo de carreira.' },
        { t: 'Diagnóstico de inglês + perfil', d: 'Avaliamos seu nível de inglês e onde você quer chegar.' },
        { t: 'Conexão com mentor experiente', d: 'Brasileiro que já vive a carreira internacional te guia direto.' },
        { t: 'Treino com IA · entrevistas e turnos', d: 'Apps construídos por quem trabalha na área. Inglês real.' },
        { t: 'Recrutamento com parceiros oficiais', d: 'Cruzeiros, Dubai, Europa. Conexão direta, sem intermediários.' },
      ],
    },
    apps: {
      kicker: 'Apps de IA · feitos por mentores',
      title1: 'Treine antes',
      title2: 'de chegar.',
      sub: 'Inglês real do dia a dia da hospitalidade. Sem aula chata. Você pratica como se já estivesse no turno.',
      app1: { tag: 'WELCOME TO THE CLUB', name: 'Career Simulator', d: 'IA simula entrevistas reais de cruzeiros e hotéis 5★. Em inglês, com correção do mentor.' },
      app2: { tag: 'ON DUTY', name: 'Shift Simulator', d: 'Áudio real de hóspedes, decisões em tempo real, feedback por turno em inglês.' },
      cta: 'Treinar grátis',
    },
    gallery: {
      kicker: 'Nosso blog',
      title1: 'A indústria',
      title2: 'em tempo real.',
      sub: 'Vagas, salários, embarques, mudanças de visto, novos hotéis abrindo. Tudo o que acontece na hospitalidade global, contado por quem vive lá dentro.',
      readMore: 'Ler post',
      readAll: 'Ver todos os posts',
      posts: [
        { tag: 'Mercado', date: '14 Mar', title: 'Atlantis abre 120 vagas para a alta temporada', excerpt: 'Recrutamento via parceiro oficial começa agora. Salários atualizados.', featured: true },
        { tag: 'Cruzeiros', date: '08 Mar', title: 'MSC anuncia novos embarques no Mediterrâneo', excerpt: 'Contratos de 6 meses com tudo incluso e tips em USD.' },
        { tag: 'Visto', date: '02 Mar', title: 'Espanha facilita visto para hospitalidade', excerpt: 'O que muda para brasileiros que já têm experiência.' },
        { tag: 'Salários', date: '24 Fev', title: 'Quanto ganha um Maître em Dubai em 2025', excerpt: 'Salário base + service charge + tips. Os números reais.' },
      ],
    },
    trusted: {
      kicker: 'Parceiros oficiais',
      title1: 'Quem confia',
      title2: 'no nosso hub.',
    },
    cta: {
      title1: 'Sua carreira lá fora',
      title2: 'começa numa conversa.',
      sub: 'Fale com a gente no WhatsApp. Sem cadastro, sem promessa vazia. Só uma conversa real sobre onde você quer chegar.',
      btn1: 'Falar no WhatsApp',
      btn2: 'Conhecer mentores',
    },
    footer: {
      tag: 'Hub de mentoria para brasileiros que querem viver de carreira internacional. Inglês como ferramenta. Mundo como destino.',
      contact: {
        title: 'Fale com a gente',
        wa: '+55 71 9 9999-0000',
        email: 'contato@brazilabroad.com',
        phone: '+55 71 3000-0000',
        addr: 'Av. Tancredo Neves, 1632 · Sala 405 · Salvador, BA · Brasil',
      },
      cols: [
        { t: 'Hub', l: ['Mentores', 'Como funciona', 'Apps de IA', 'Histórias reais'] },
        { t: 'Carreira', l: ['Cruzeiros', 'Hotéis 5★', 'Restaurantes', 'Inglês na hospitalidade'] },
        { t: 'Sobre', l: ['Ricardo Rogério', 'Parceiros oficiais', 'Trabalhe conosco', 'Termos'] },
      ],
      copy: '© 2026 Brazil Abroad · CNPJ 00.000.000/0001-00 · Salvador · Dubai · Mundo',
    },
    about: {
      kicker: 'Quem está com você',
      title1: 'Ricardo',
      title2: 'Rogério.',
      role: 'Fundador · 15 anos na hospitalidade de luxo',
      body: 'Saí de Salvador para o mundo aos 23 anos. Hoje sou Maître no Atlantis The Royal em Dubai, onde sirvo hóspedes que pagam US$ 30 mil por noite. Antes disso: Amazónico, Casa Blanca, Ling Ling. Conheço cada porta dessa indústria — e como brasileiro com inglês certo entra por ela.',
      body2: 'O Brazil Abroad nasceu pra encurtar o caminho que eu fiz. Sem agente. Sem promessa de curso mágico. Mentoria 1–1, inglês direcionado pra hospitalidade, e conexão real com quem contrata.',
      cta: 'Agendar consultoria 1–1',
      cta2: 'Falar no WhatsApp',
      badges: ['Atlantis The Royal · Dubai', 'Amazónico · Dubai', 'MSC Cruises', '15 anos na área'],
    },
    jobs: {
      kicker: 'Mural ao vivo',
      title1: 'Fique por dentro',
      title2: 'das vagas.',
      sub: 'Vagas atualizadas todo mês via nossos parceiros oficiais. Salários em USD/EUR/AED, livre de imposto em alguns destinos. Faça sua avaliação gratuita e receba as compatíveis no e-mail.',
      cta: 'Faça sua avaliação gratuita',
      list: [
        { role: 'Waiter · Fine Dining', co: 'Atlantis The Royal', loc: 'Dubai, UAE', salary: 'AED 6.500/mês', tax: 'Livre de imposto', tag: 'Hot', logo: 'A' },
        { role: 'F&B Server', co: 'MSC Cruises', loc: 'Mar Mediterrâneo', salary: 'USD 2.400/mês + tips', tax: 'Tudo incluído', tag: 'Embarque próx.', logo: 'M' },
        { role: 'Guest Relations', co: 'Hilton 5★', loc: 'Madrid, Espanha', salary: 'EUR 2.100/mês', tax: 'Visto patrocinado', tag: 'Europa', logo: 'H' },
        { role: 'Head Server', co: 'Amazónico', loc: 'Dubai, UAE', salary: 'AED 8.000/mês', tax: 'Acomodação inclusa', tag: 'Senior', logo: 'A' },
        { role: 'Sommelier Junior', co: 'Casa Blanca', loc: 'Dubai, UAE', salary: 'AED 7.000/mês', tax: 'Livre de imposto', tag: 'Wine', logo: 'C' },
        { role: 'Bartender', co: 'Royal Caribbean', loc: 'Caribe', salary: 'USD 2.800/mês + tips', tax: 'Tudo incluído', tag: 'Cruise', logo: 'R' },
        { role: 'Restaurant Manager', co: 'Ling Ling', loc: 'Dubai, UAE', salary: 'AED 12.000/mês', tax: 'Bonus anual', tag: 'Lead', logo: 'L' },
        { role: 'Front Desk Agent', co: 'Four Seasons', loc: 'Lisboa, Portugal', salary: 'EUR 1.700/mês + tips', tax: 'Visto patrocinado', tag: 'Europa', logo: 'F' },
      ],
    },
    english: {
      kicker: 'Inglês direcionado',
      title1: 'Não é inglês',
      title2: 'genérico.',
      sub: 'Você aprende o inglês que vai usar no turno. Vocabulário de fine dining, frases de check-in/out, comunicação com hóspede VIP, terminologia de cruzeiro. Treinado por quem trabalha na área.',
      cards: [
        { tag: 'F&B · Serviço de mesa', t: 'Fine Dining English', d: 'Apresentação de pratos, harmonização de vinhos, lidar com restrições e alergias.', sample: '"May I suggest pairing this with a glass of …"' },
        { tag: 'Front Desk · Hotéis 5★', t: 'Check-in / Check-out', d: 'Frases padrão, lidando com reclamações, upgrades, problemas de reserva.', sample: '"I\'ll personally take care of that for you, sir."' },
        { tag: 'Cruzeiros', t: 'Cruise Vocabulary', d: 'Termos de bordo, anúncios, comunicação em emergência.', sample: '"Muster station drill at 1600 hours."' },
        { tag: 'Guest Relations', t: 'VIP Communication', d: 'Tom apropriado, expressar empatia, antecipar necessidades.', sample: '"Allow me to make this right for you."' },
      ],
    },
    testimonials: {
      kicker: 'Por dentro da consultoria',
      title1: 'Como é uma',
      title2: 'consultoria.',
      sub: 'Três conversas reais, sem corte, com brasileiros que vieram para a consultoria. Veja como funciona antes de marcar a sua.',
      items: [
        { kicker: 'Consultoria real #1', title: 'Garçom com experiência no Brasil', vid: 'ir7gkXlVIQw' },
        { kicker: 'Consultoria real #2', title: 'Primeiro passo para o exterior', vid: 'Y7SL63fiDU0' },
        { kicker: 'Consultoria real #3', title: 'Com nosso parceiro recrutador', vid: '6EAJYsQoCZs' },
      ],
    },
  },
  en: {
    nav: { mentors: 'Mentors', road: 'How it works', apps: 'AI apps', gallery: 'Blog', trusted: 'Partners', start: 'Talk on WhatsApp' },
    hero: {
      kicker: 'Mentorship hub · Brazilians worldwide',
      title1: 'Your English,',
      title2: 'your career abroad.',
      sub1: 'We connect Brazilians with experienced mentors at cruises, 5★ hotels and award-winning restaurants.',
      sub2: 'English is the tool. Career is the destination.',
      cta1: 'Talk to a mentor',
      cta2: 'How it works',
      scroll: 'Scroll to explore',
    },
    stats: {
      kicker: 'Why we are different',
      title1: 'Not a course.',
      title2: 'Real mentorship.',
      label1: 'Average monthly earnings of our students abroad',
      label2: 'Active mentors · cruises, Dubai, Europe',
      label3: 'Years of combined experience in our network',
      label4: 'Brazilians guided into international careers',
    },
    mentors: {
      kicker: 'Our mentor network',
      title1: 'Who',
      title2: 'guides you.',
      sub: 'Brazilian professionals living the international career. They have already walked the path you want to take.',
      list: [
        { name: 'Ricardo Rogério', role: 'Founder · Maître Atlantis Dubai', tag: '15 years · Dubai', bio: 'Luxury hospitality from Brazil to the Middle East.' },
        { name: 'Carla Mendes', role: 'F&B Manager · MSC Cruises', tag: '8 years at sea', bio: 'Over 60 countries visited on cruise contracts.' },
        { name: 'Diego Almeida', role: 'Head Server · Amazónico Dubai', tag: 'Fine dining', bio: 'From Salvador to the world\'s best restaurants.' },
        { name: 'Letícia Ramos', role: 'Guest Relations · Hilton 5★', tag: 'Europe', bio: 'Fluent English, career across three continents.' },
      ],
    },
    road: {
      kicker: 'How it works · five steps',
      title1: 'Your',
      title2: 'mentorship journey.',
      steps: [
        { t: 'First chat · WhatsApp', d: 'You talk to our team. We listen to your career goal.' },
        { t: 'English & profile diagnostic', d: 'We assess your English level and where you want to go.' },
        { t: 'Match with experienced mentor', d: 'A Brazilian already living the international career guides you.' },
        { t: 'Train with AI · interviews and shifts', d: 'Apps built by mentors in the field. Real English.' },
        { t: 'Recruitment with official partners', d: 'Cruises, Dubai, Europe. Direct line. No middlemen.' },
      ],
    },
    apps: {
      kicker: 'AI apps · built by mentors',
      title1: 'Train before',
      title2: 'you arrive.',
      sub: 'Real English from daily hospitality. No boring lessons. You practice as if you were already on shift.',
      app1: { tag: 'WELCOME TO THE CLUB', name: 'Career Simulator', d: 'AI simulates real interviews from cruises and 5★ hotels. In English, with mentor feedback.' },
      app2: { tag: 'ON DUTY', name: 'Shift Simulator', d: 'Real guest audio, real-time decisions, English feedback per shift.' },
      cta: 'Train free',
    },
    gallery: {
      kicker: 'Our blog',
      title1: 'The industry',
      title2: 'in real time.',
      sub: 'Jobs, salaries, embarkations, visa changes, new hotels opening. Everything that happens in global hospitality, told by people inside it.',
      readMore: 'Read post',
      readAll: 'See all posts',
      posts: [
        { tag: 'Market', date: 'Mar 14', title: 'Atlantis opens 120 jobs for high season', excerpt: 'Recruitment via official partner starts now. Updated salaries.', featured: true },
        { tag: 'Cruises', date: 'Mar 08', title: 'MSC announces new Mediterranean boardings', excerpt: '6-month contracts, all-inclusive, tips in USD.' },
        { tag: 'Visa', date: 'Mar 02', title: 'Spain eases visa for hospitality workers', excerpt: 'What changes for Brazilians with experience.' },
        { tag: 'Salaries', date: 'Feb 24', title: 'How much a Maître earns in Dubai in 2025', excerpt: 'Base salary + service charge + tips. The real numbers.' },
      ],
    },
    trusted: {
      kicker: 'Official partners',
      title1: 'Who trusts',
      title2: 'our hub.',
    },
    cta: {
      title1: 'Your career abroad',
      title2: 'starts with a chat.',
      sub: 'Talk to us on WhatsApp. No signup, no empty promise. Just a real conversation about where you want to go.',
      btn1: 'Talk on WhatsApp',
      btn2: 'Meet mentors',
    },
    footer: {
      tag: 'Mentorship hub for Brazilians who want to live an international career. English as the tool. The world as the destination.',
      contact: {
        title: 'Talk to us',
        wa: '+55 71 9 9999-0000',
        email: 'contact@brazilabroad.com',
        phone: '+55 71 3000-0000',
        addr: 'Av. Tancredo Neves, 1632 · Suite 405 · Salvador, BA · Brazil',
      },
      cols: [
        { t: 'Hub', l: ['Mentors', 'How it works', 'AI apps', 'Real stories'] },
        { t: 'Career', l: ['Cruises', '5★ Hotels', 'Restaurants', 'English in hospitality'] },
        { t: 'About', l: ['Ricardo Rogério', 'Official partners', 'Work with us', 'Terms'] },
      ],
      copy: '© 2026 Brazil Abroad · CNPJ 00.000.000/0001-00 · Salvador · Dubai · World',
    },
    about: {
      kicker: 'Who stands with you',
      title1: 'Ricardo',
      title2: 'Rogério.',
      role: 'Founder · 15 years in luxury hospitality',
      body: 'I left Salvador for the world at 23. Today I am Maître at Atlantis The Royal in Dubai, where I serve guests paying US$ 30k a night. Before that: Amazónico, Casa Blanca, Ling Ling. I know every door of this industry — and how a Brazilian with the right English walks through them.',
      body2: 'Brazil Abroad was born to shorten the path I took. No agent. No magic-course promise. 1–1 mentorship, English directed for hospitality, and real connection to those who hire.',
      cta: 'Book 1–1 consultation',
      cta2: 'Talk on WhatsApp',
      badges: ['Atlantis The Royal · Dubai', 'Amazónico · Dubai', 'MSC Cruises', '15 years in field'],
    },
    jobs: {
      kicker: 'Live mural',
      title1: 'Fresh hospitality',
      title2: 'jobs.',
      sub: 'Jobs updated monthly via our official partners. Salaries in USD/EUR/AED, tax-free in some destinations. Take your free assessment and receive matches in your email.',
      cta: 'Take your free assessment',
      list: [
        { role: 'Waiter · Fine Dining', co: 'Atlantis The Royal', loc: 'Dubai, UAE', salary: 'AED 6,500/mo', tax: 'Tax-free', tag: 'Hot', logo: 'A' },
        { role: 'F&B Server', co: 'MSC Cruises', loc: 'Mediterranean', salary: 'USD 2,400/mo + tips', tax: 'All inclusive', tag: 'Boarding', logo: 'M' },
        { role: 'Guest Relations', co: 'Hilton 5★', loc: 'Madrid, Spain', salary: 'EUR 2,100/mo', tax: 'Visa sponsored', tag: 'Europe', logo: 'H' },
        { role: 'Head Server', co: 'Amazónico', loc: 'Dubai, UAE', salary: 'AED 8,000/mo', tax: 'Housing inc.', tag: 'Senior', logo: 'A' },
        { role: 'Junior Sommelier', co: 'Casa Blanca', loc: 'Dubai, UAE', salary: 'AED 7,000/mo', tax: 'Tax-free', tag: 'Wine', logo: 'C' },
        { role: 'Bartender', co: 'Royal Caribbean', loc: 'Caribbean', salary: 'USD 2,800/mo + tips', tax: 'All inclusive', tag: 'Cruise', logo: 'R' },
        { role: 'Restaurant Manager', co: 'Ling Ling', loc: 'Dubai, UAE', salary: 'AED 12,000/mo', tax: 'Annual bonus', tag: 'Lead', logo: 'L' },
        { role: 'Front Desk Agent', co: 'Four Seasons', loc: 'Lisbon, Portugal', salary: 'EUR 1,700/mo + tips', tax: 'Visa sponsored', tag: 'Europe', logo: 'F' },
      ],
    },
    english: {
      kicker: 'Targeted English',
      title1: 'Not generic',
      title2: 'English.',
      sub: 'You learn the English you will actually use on shift. Fine dining vocabulary, check-in/out phrases, VIP communication, cruise terminology. Trained by people in the field.',
      cards: [
        { tag: 'F&B · Table service', t: 'Fine Dining English', d: 'Plate presentation, wine pairing, handling restrictions and allergies.', sample: '"May I suggest pairing this with a glass of …"' },
        { tag: 'Front Desk · 5★ Hotels', t: 'Check-in / Check-out', d: 'Standard phrases, handling complaints, upgrades, reservation issues.', sample: '"I\'ll personally take care of that for you, sir."' },
        { tag: 'Cruises', t: 'Cruise Vocabulary', d: 'On-board terms, announcements, emergency communication.', sample: '"Muster station drill at 1600 hours."' },
        { tag: 'Guest Relations', t: 'VIP Communication', d: 'Appropriate tone, expressing empathy, anticipating needs.', sample: '"Allow me to make this right for you."' },
      ],
    },
    testimonials: {
      kicker: 'Inside the consultation',
      title1: 'What a',
      title2: 'consultation looks like.',
      sub: 'Three real conversations, uncut, with Brazilians who came for consultation. See how it works before booking yours.',
      items: [
        { kicker: 'Real consultation #1', title: 'Waiter with experience in Brazil', vid: 'ir7gkXlVIQw' },
        { kicker: 'Real consultation #2', title: 'First step abroad', vid: 'Y7SL63fiDU0' },
        { kicker: 'Real consultation #3', title: 'With our recruiter partner', vid: '6EAJYsQoCZs' },
      ],
    },
  },
} as const;

export type Lang = 'pt' | 'en';
export type Strings = typeof STR.pt;
